### PR TITLE
Deal with API errors

### PR DESCRIPTION
**Pull request by jackfranklin**
- updated middleman to pass errors back
- more consistently use cb(err, data) convention
- deal with 503 errors (Heroku down)

### CODE REVIEW

**Comment by jackfranklin** [comment]
@phuu

**Comment by jackfranklin** [comment]
Eurgh, this isn't building because some modules we depend on have dependencies that use the new `^0.2.0` syntax, which Node 0.8 doesn't like. Time to ditch 0.8 support?

**Comment by jackfranklin** [comment]
@phuu thoughts on above?

**Comment by jackfranklin** [comment]
I'm confused why this branch fails, because there are none of the ^ dependencies in the package.json.

**Comment by jackfranklin** [comment]
So one of our dependencies has a ^ hidden in it somewhere:

```
npm ERR! Error: No compatible version found: minimatch@'^0.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.4","0.0.5","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.3.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.26/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.26/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 2.6.32-042stab079.5
npm ERR! command "/home/travis/.nvm/v0.8.26/bin/node" "/home/travis/.nvm/v0.8.26/bin/npm" "install"
npm ERR! cwd /home/travis/build/jackfranklin/pulldown
npm ERR! node -v v0.8.26
npm ERR! npm -v 1.2.30
```

I hate this.

Not going to merge this because doing so drops 0.8 which seems silly. @phuu any pointers welcome. Screw dependencies.

**Comment by lloydwatkin** [comment]
If running via travis then a simple:

``` yaml
before_install:
  - npm i -g npm
```

Will fix this for you :)

**Comment by lloydwatkin** [comment]
https://github.com/jackfranklin/pulldown/pull/93

**Comment by jackfranklin** [comment]
@lloydwatkin you might just be my hero.

**Pull request merged**
