### PR TITLE
No new needed

### PR DESCRIPTION
**Pull request by jackfranklin**
Changed Pulldown's structure so it no longer has to be instantiated with `new`.

### CODE REVIEW

**Comment by jackfranklin** [comment]
While the thought is in my mind, @phuu the CLI.js also has to be instantiated with `new` but as far as I can see there's literally no benefit to doing this - so may also refactor the CLI as I have done with the main Pulldown module.

**Comment by tgvashworth** [comment]
I approve of this message.

**Comment by jackfranklin** [comment]
Great. I'll add that in and then merge.

**Comment by jackfranklin** [comment]
@phuu see last commit & pls merge if you're happy :)

**Comment by tgvashworth** [comment]
Hotness.

**Pull request merged**
